server:
  port: 8080

spring:
  application:
    name: rippler-backend
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB

logging:
  level:
    com.ayush.rippler: DEBUG
